name: Issue Bot

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  reply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueTitle = context.payload.issue.title || 'No Title Provided';
            const issueBody = context.payload.issue.body || 'No description provided.';

            try {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `
                  Hi 👋 — thanks for opening this issue!

                  We really appreciate you taking the time to report a problem or suggest an improvement.
                  Here's what happens next:
                  - Our team will review your feedback soon.
                  - If applicable, feel free to share more details (e.g., screenshots, steps to reproduce) in a comment below.

                  🔗 **Issue Summary:**
                  > **${issueTitle}**

                  📋 **Your Message:**
                  > ${issueBody}

                  Thanks again for helping improve this project! 🌟`
              });
            } catch (error) {
                console.error('Error posting comment:', error);
                throw error; // Fail the workflow if the comment cannot be posted
            }
